import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import NavBar from "@/components/ui/navbar/nav-bar";
import SideBar from "@/components/ui/sidebar/side-bar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <div style={{ display: "flex" }}>
            <SideBar />
            <NavBar />
            <main style={{ flex: 1, padding: "16px" }}>
              {children}
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
